### ISSUE TITLE
Site Goals and planning

### ISSUE THREAD

**Issue by brb3** [devanooga/devanooga.com#1]
Here's the stuff we want to show on the site:
- About page (home page)
- CoC
- Members list of some kind
- Way for people to request Slack invites
- List of open source things around town (projects, etc)
- A logo
- Job listings eventually

We need to decide on a tech stack to work with. What are your recommendations?

**Comment by t-richards** [comment]
For low(er than most other stacks) maintenance purposes, I'd highly recommend a static site stack. [Jekyll](https://jekyllrb.com/) is a very approachable tool to accomplish this.

Others do exist but they're not nearly as popular as Jekyll. https://www.staticgen.com/

**Comment by brb3** [comment]
Yea, I think it's probably not a bad idea to go ahead and setup a Jekyll site. If our needs change later we can always scrap it. Plus we should be able to re-use our Jekyll assets on another platform pretty easily.

**Comment by StrangeWill** [comment]
I'm not the _biggest_ fan of Jekyll, but it's the one I know and it is pretty extensible.

**Comment by StrangeWill** [comment]
For anything we need forms on the site for, Netlify has awesome support for us: https://www.netlify.com/docs/form-handling/

We could do some quasi-interactive stuff where we use their API to pull form responses and post it to the site for stuff like job postings (in lieu of a full platform).

**Comment by StrangeWill** [comment]
I'm going to close this being as the site is up and there are issues relevant the any other line items now.
