### ISSUE TITLE
gravatar hash

### ISSUE THREAD

**Issue by DigTK** [devanooga/devanooga.com#101]
The explanation on https://github.com/devanooga/devanooga.com#submitting-your-member-profile tells people to use a third party tool to get your gravatar hash, but gravatar has its own tool under https://en.gravatar.com/site/check/

Is there anything speaking against changing it to that?

**Comment by agarzola** [comment]
I had no idea about this. There’s no reason not to use the official tool. Want to submit a PR for it, @DigTK?

**Comment by DigTK** [comment]
Oh boy oh boy

**Comment by DigTK** [comment]
Whoops I forgot to mention this issue in the commit, oh well

**Comment by StrangeWill** [comment]
I liked it because it gave you the  hash on the page, instead of having to inspect the element.
