### ISSUE TITLE
AdWords landing page featuring #opportunities

### ISSUE THREAD

**Issue by katize** [devanooga/devanooga.com#108]
We need a landing page for AdWords, targeting US citizens outside of Chattanooga, who are searching for Chattanooga development, IT, tech, etc. We assume they're mostly looking for job opportunities in this area, so a landing page should include:

# Chattanooga IT Community
Short description of devanooga (can be the "tinkerers" line)
_The devanooga community communicates via Slack. If you're looking for job or project opportunities in the Chattanooga area, join our Slack Team and hop into the Opportunities channel._

At the bottom, a CTA to "Join our Slack Team"

**Comment by katize** [comment]
@agarzola HEY

**Comment by agarzola** [comment]
@katize Why shouldn’t this campaign point to the home page?

**Comment by StrangeWill** [comment]
I think the idea is we can also pitch more "come to chattanooga" type verbiage.

**Comment by katize** [comment]
@agarzola  Right, this is going to target non-Chattanoogans, so if we take them to the homepage, it doesn't mention what about devanooga would appeal to them. These will be people searching for things like "chattanooga ruby jobs," "chattanooga development jobs" "chattanooga jobs," etc. I want to make sure they understand why it's worth joining the group even before they make their move.
