### ISSUE TITLE
Email subscription style issue

### ISSUE THREAD

**Issue by Willamin** [devanooga/devanooga.com#109]
In Chrome, the email address + submit button for the email submission looks great, but in Safari, it gets shuffled around and doesn't look super good. Here are screenshots of both for comparison.

Chrome:
![devanooga-chrome](https://cloud.githubusercontent.com/assets/7304492/26588486/79d1c110-4523-11e7-8159-57ca3abbdeb7.png)

Safari:
![devanooga-safari](https://cloud.githubusercontent.com/assets/7304492/26588492/7bef3806-4523-11e7-93e4-e77f1e2800c5.png)

**Comment by StrangeWill** [comment]
Safari I fuckin' swear. 
![image](https://cloud.githubusercontent.com/assets/1322565/26588547/a80c7192-4523-11e7-8709-515cb6fe3401.png)

**Comment by agarzola** [comment]
Thanks for reporting this, @Willamin. I recently encountered a similar Safari-related issue on another project and forgot to check for it here. I’ll address this tonight.

**Comment by agarzola** [comment]
Crashed last night and forgot about this. I’ll address it during hacknight.
