### ISSUE TITLE
Slack handle on members page

### ISSUE THREAD

**Issue by DigTK** [devanooga/devanooga.com#111]
Can we add the Slack handle to the members page? Something like this:

![image](https://cloud.githubusercontent.com/assets/4950390/26658879/fb28250c-463a-11e7-9061-82cbc5eacf09.png)

**Comment by agarzola** [comment]
It’s a great idea to have the Slack handle visible on the members page. 👍  But I don’t think it should be another item in the list of online profiles. We should chew on this for a bit. Ideas welcome.
