### ISSUE TITLE
Link to an RSS feed leads to a 404

### ISSUE THREAD

**Issue by appel** [devanooga/devanooga.com#141]
There's a link to an RSS feed in the source code, which leads to a 404:

````
<link rel="alternate" type="application/rss+xml" title="devanooga" href="https://devanooga.com/feed.xml" />
````

**Comment by agarzola** [comment]
Shitsnacks! Thanks for bringing this to our attention. If you’re up for the challenge, you’re more than welcome to fork and submit a pull-request! If not, I’ll try to tackle this tonight unless someone else beats me to it.

**Comment by t-richards** [comment]
May I suggest https://github.com/jekyll/jekyll-feed ?

**Comment by appel** [comment]
@agarzola whish I could help but I'm afraid my Ruby game is sorely lacking ;)

**Comment by appel** [comment]
https://github.com/devanooga/devanooga.com/pull/142

**Comment by appel** [comment]
Seems to works like a charm!
https://www.devanooga.com/feed.xml
