### ISSUE TITLE
Code of Conduct Anchors

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.com#157]
Would be nice to be able to link to individual rules...

Can we highlight on anchor selector alone? @agarzola?

**Comment by agarzola** [comment]
Not sure what you mean by _highlight on anchor selector alone_. Do you know of an example of this?

**Comment by StrangeWill** [comment]
http://jsfiddle.net/davidThomas/NGyVL/

That, which is pure CSS, so yeah I'll be doing that later...

**Comment by agarzola** [comment]
Oh, sure. We do something similar with members on the members page: https://devanooga.com/members#strangewill

**Comment by StrangeWill** [comment]
Done in PR #207
