### ISSUE TITLE
Derelict Slack channels

### ISSUE THREAD

**Issue by DigTK** [devanooga/devanooga.com#167]
The following channels haven't seen a lot of use lately and are candidates for deletion/archival (should probably ask the current channel members in here first if they're okay with the archival of the channel):

#analytics
#android
#business
#dontgetmestarted
#dontgetwillstarted
#electron
#elixir
#freelance
#go
#jobs
#math
#mce
#meyouandi
#parking-hall-of-shame
#philosophy
#python
#r
#rum-lang
#rust
#shady_dealings
#signalmountain
#sysadmins
#tadpole
#television (people are using the #movies channel for all television talk)
#wce
#z

**Comment by StrangeWill** [comment]
Kept:

#analytics
#electron
#elixir
#freelance
#go
#python
#signalmountain
