### ISSUE TITLE
Slack sign-up page looks awful

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.com#18]
Ticketing this out because we know it to be the case.

@patriotbob is currently looking at adding some JS (jQuery?) support to the site and to probably just post directly to the form (we may have to fork/tweak the project if CORS isn't configured to do this).

**Comment by agarzola** [comment]
What’s the status of this?

**Comment by StrangeWill** [comment]
@patriotbob said he'd work on this, and he lied.

Maybe I'll fix it. I think the biggest annoyance is the Heroku app takes forever to boot.

**Comment by 7279616e** [comment]
> the Heroku app takes forever to boot
Part of the stipulation of the free Heroku plan, unfortunately. Openshift did have a free plan with no shutoff during inactivity, but it appears that they have reduced it to a 30 day trial.

**Comment by StrangeWill** [comment]
I've considered putting in information that'll allow me to have enough hours a month to keep it online 24/7 and just pointing StatusCake at it to keep it awake, awful workaround though...

**Comment by StrangeWill** [comment]
Verified the Heroku account that free node is on, set up StatusCake to kick it every 15 minutes -- should keep it awake at least.

**Comment by 7279616e** [comment]
I've added it to my UptimeRobot and StatusGator accounts as well.

**Comment by 7279616e** [comment]
When you say the slack page looks awful, do you mean you would like the contents of the iframe to resemble the design of the remainder of the devanooga site? 

Or do you mean you would like someone to edit the [public folder for the slack-invite-app here](https://github.com/outsideris/slack-invite-automation/tree/master/public), and then redeploy it? 

If the later, I imagine we'll need a public repo of that fork?

**Comment by StrangeWill** [comment]
The main issue is the background of that page, we've considered both writing our own form to post to that application or to just fork the app and change the template. Due to CORS both requires forking the project.

**Comment by 7279616e** [comment]
> Heroku app takes forever to boot

It looks like the uptime monitor solution works [fairly well](http://i.imgur.com/kTSrPar.png) so far. However, they may have some sort of filtering to detect that given time. No worries, regardless. 

> Due to CORS both requires forking the project.

Since I imagine the only thing different from the original are the devanooga env variables (api token, etc), I forked it to tinker.

**Comment by 7279616e** [comment]
Conferred with @StrangeWill about desired colors. He helped me find a few issues with my tweak. When he pushed the update, let me know if you find anything that needs to be fixed. Happy to do so.

**Comment by StrangeWill** [comment]
![image](https://cloud.githubusercontent.com/assets/1322565/24336421/1a9ccf1c-125d-11e7-8deb-87ab37d672d7.png)


Lots better 👍 Thanks!

**Comment by agarzola** [comment]
@7279616e 🎉  Nice job! Thanks for pitching in, sir!
