### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by brb3** [devanooga/devanooga.com#25]
Do we want people to have `@devanooga.com` email addresses?
Is that a "members-only" kind of thing?
How will that be hosted?
_Discuss_

**Comment by StrangeWill** [comment]
At _best_ I'm going to use it as a forwarder, and it better be pretty heavily spam protected.

Likely: won't use it at all.

**Comment by agarzola** [comment]
I’m fine with there only being an admin@, or a hello@, or a support@. I certainly don’t need yet another email address to keep track of/hand out.

**Comment by brb3** [comment]
Ok, yea, the last thing we need is more email addresses.

For now, I'll just worry about giving myself a way to send/receive mail as `admin@devanooga.com`.

**Comment by 7279616e** [comment]
Agree with "last thing we need is more email addresses". 

However, in the event that any services that are available to members of non-profits would require email accounts (in the far off future), there is [Migadu](https://www.migadu.com/en/index.html)

**Comment by agarzola** [comment]
Migadu looks great, @7279616e. Thanks for bringing it to our attention.

**Comment by brb3** [comment]
Migadu _does_ look great. Any objections to me setting it up? There's a free plan that just includes a Migadu advertisement in the signature of all outgoing messages. Check out the [pricing](https://www.migadu.com/en/pricing.html).

If no objections from anyone, I'll go ahead and set this up for the admin@ email address.

CC: @StrangeWill

**Comment by agarzola** [comment]
I ain’t against that.

**Comment by StrangeWill** [comment]
> Any objections to me setting it up?

Only concern I ever have about platforms like this is how decent anti-spam is. Trying it out isn't really a problem.

**Comment by 7279616e** [comment]
> how decent anti-spam is
There will certainly be a weaker spam filter than GOOG/MS. Thats just part of being a smaller provider. If I recall correctly, its just two guys running Migadu. At this point, I imagine the group only needs an admin@ accounts, no? 

And even when things progress, and it seems optimal for users to have mail accounts under the devanooga domain, I imagine most will forward/POP through a service with a stronger spam filter.

**Comment by brb3** [comment]
Ok, got Migadu setup and DNS records in place.

It will probably take a while for DNS to propagate. Once that's all wrapped up, I'll close this issue.

**Comment by brb3** [comment]
Email is all setup now. 👍
