### ISSUE TITLE
Code of Conduct improvements

### ISSUE THREAD

**Issue by brb3** [devanooga/devanooga.com#36]
Re: #12 comments

**Comment by camilopayan** [comment]
Needs a list of the administrators to contact

**Comment by StrangeWill** [comment]
I like the idea of singling out admins on the membership page, and having the CoC point at it (originally @agarzola's idea).

For now we should probably just toss the handles in there.

**Comment by agarzola** [comment]
Just noticed the CoC is missing [this suggestion](https://github.com/devanooga/devanooga.github.io/pull/12#discussion_r98354893) from #12. Is this an oversight, or do we just not want that language in there?

**Comment by StrangeWill** [comment]
@agarzola Hmm I still think we're trying to hammer out how we want to approach that entirely -- while yes discussions and whatnot will be public, I like the idea of having a published mod log... question is where/how do we keep that...

**Comment by StrangeWill** [comment]
Addresesd @agarzola's point in PR #208.
