### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.com#43]
There was some interest expressed in a blog by a few Slack members (idea by mckendr, Willamin also expressed interest). This could be really fun if we can get a handful of regular writers. We could write about tech stuff going on (various events), interesting articles and the writer's take on the subject, or generic Chattanooga happenings.

I love the idea, should probably see about getting something together in Jekyll at some point.

**Comment by StrangeWill** [comment]
Point of interest: is using Git to do so too much of a high bar of entry?

Do I just wait for a user to complain about it (feel free to complain)?

**Comment by 7279616e** [comment]
> Point of interest: is using Git to do so too much of a high bar of entry?

I asked, because I don't know what level of 'beginner' the group will attract, or hopes to attract. It was simply a question/suggestion of ignorance. No complaints here.

**Comment by Willamin** [comment]
Since we're a developer-oriented organization, I don't think git is a high bar of entry. However, there may come a time when someone wants to make a post and either has never used git before or is new to developing entirely. In that case, most of what would need to be done to get a blog post submitted could be done only using GitHub's website, so a paragraph or two could help point people in the right direction.

**Comment by 7279616e** [comment]
^ That is a solid work-around. Just some sort of note that encourages that category of user to freely ask for help, or a brief note on how to use the site for a blog post PR.

**Comment by StrangeWill** [comment]
> I asked, because I don't know what level of 'beginner' the group will attract, or hopes to attract. It was simply a question/suggestion of ignorance. No complaints here.

It is a good point though, we have instructions for getting on our members page for non-Git users.

> Since we're a developer-oriented organization, I don't think git is a high bar of entry. 

I've worked at quite a few places where teaching devs Git was out of the question, but at the same time they weren't the kind of devs to get involved with a local community anyway unless they were getting paid to do so...

**Comment by brb3** [comment]
Implemented in #72
