### ISSUE TITLE
Structured Data For SEO

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.com#45]
Webmaster tools whines that we don't have any (duh).

https://developers.google.com/search/docs/guides/enhance-site

SEO would be big for us, so lets see where this works well for us. Will definitely be a big one for our blog feature (#43).

**Comment by t-richards** [comment]
I can highly recommend https://github.com/jekyll/jekyll-seo-tag for making this structured stuff happen without much fuss.

**Comment by StrangeWill** [comment]
Implemented jekyll-seo-tag in #60, mostly need to work on content...
