### ISSUE TITLE
Donation Link

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.com#57]
* Need a Paypal account
* Need an Ally/Simple account?
* Do we need to be NPO before we take donations?
* Need a way to keep track of finances in a transparent manner (probably just Google Sheets for  now)

**Comment by tmbeihl** [comment]
https://donorbox.org/pricing/ is free until we get $1000/month in donations

**Comment by StrangeWill** [comment]
Ohhh recurring donations is pretty tempting, wondering what the bite on that would be.

**Comment by tmbeihl** [comment]
I bet we could easily get 2-300/month in recurring donations.

**Comment by StrangeWill** [comment]
Signed up with Ally bank today, transferred $10 into it to get it kick started (consider it my donation for now at least).

Signed up for Stripe, invited @brb3, signed up for Donorbox but it appears an org cannot have multiple accounts in it... boo. Will probably hand that account over to @brb3 at some point then...

Willl probably start up a Google sheet soon...

**Comment by tmbeihl** [comment]
One donorbox account per stripe account, but we can have multiple donation pages/buttons for different projects.

**Comment by StrangeWill** [comment]
Well was more hoping for multiple logins into Donorbox, eg: so I can have my own login and @brb3 can and maybe get one for @agarzola considering he does design work, etc. etc. It doesn't appear that I can do this.

Not a huge deal though.

**Comment by StrangeWill** [comment]
OK Cool, @tmbeihl just showed me that it's implicit via Stripe. Log in via Stripe and it does the rest. 👍

**Comment by StrangeWill** [comment]
#59 implements this.

**Comment by agarzola** [comment]
#59 was merged, but apparently _some of us_ don’t like to trigger closing issues from commit messages.
