### ISSUE TITLE
Clicking label on form doesn't select text field

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.com#68]
On our contact us page, @t-richards pointed it out (who selects fields that way?! Oh well...), due to the missing `for` attribute on the labels.

**Comment by agarzola** [comment]
_I_ select fields that way. 😛

**Comment by StrangeWill** [comment]
WHAT IS WRONG WITH YOU PEOPLE?!

**Comment by StrangeWill** [comment]
Also: @patriotbob is like "hurr durr, write on the web for over a decade, still doesn't know what the `for` field on a label is for"

Let's be honest, I was a little curious (but apparently not curious enough).

**Comment by brb3** [comment]
Fixed in #71
