### ISSUE TITLE
Contact page looks like shit

### ISSUE THREAD

**Issue by agarzola** [devanooga/devanooga.com#69]
SRSLY

**Comment by StrangeWill** [comment]
Last commit on it was @DigTK so it's his fault.

**Comment by StrangeWill** [comment]
More accurately: http://i.imgur.com/RnLw8sc.png

**Comment by agarzola** [comment]
FTFY

**Comment by 7279616e** [comment]
Don't criticize, d00dz. @StrangeWill I think you're great, sir.  You, also, @DigTK

**Comment by StrangeWill** [comment]
I may consider sucking less this hacknight if no one else picks it up.
