### ISSUE TITLE
Improve blog appearance

### ISSUE THREAD

**Issue by agarzola** [devanooga/devanooga.com#77]
Improve the following (as reported in #78):
- [x] image positioning (center them, probably)
- [x] syntax highlighting (find a nice theme, maybe)

**Comment by brb3** [comment]
When you look at this, also go to the "blog" page and click on my name. The scroll position when you hit the member page is odd.

<img width="1055" alt="screen shot 2017-04-22 at 5 38 44 pm" src="https://cloud.githubusercontent.com/assets/1583460/25308453/958139ea-2782-11e7-8b4c-6c7b241853ee.png">

**Comment by agarzola** [comment]
Yeah, this is the age-old issue of jumping to an anchor with a fixed header. It’s better to address this in #75. In fact, if you wouldn’t mind, please add a review to that PR and mark it as _Request changes_, so that its status makes it clear there are issues that need to be addressed before it’s merged.

**Comment by agarzola** [comment]
This is done.
