### ISSUE TITLE
501(c)(3) status

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.com#81]
We should update our donations section or something detailing we're officially a 501(c)(3), I got paperwork today, awaiting the IRS website to be updated and techsoup to process the rest (10 days on TechSoup).

**Comment by agarzola** [comment]
I’ll submit a pull-request soon. Is it safe to merge that in before IRS website is updated?

**Comment by agarzola** [comment]
@StrangeWill When you get a chance, please list what information (if any) we’re required to display when taking donations as a 501(c)(3). If none is _required_, anything that’s helpful to a donor, maybe?

**Comment by agarzola** [comment]
@StrangeWill bump

**Comment by StrangeWill** [comment]
Hmm we may just update that we're a full 501(c)(3) and just handle the EIN notifications via the mail I'm supposed to send out for donors that donate that much.

**Comment by StrangeWill** [comment]
PR #113 should cover it.
