### ISSUE TITLE
Add hacknight info to our site

### ISSUE THREAD

**Issue by agarzola** [devanooga/devanooga.com#82]
This might be either (or both) of the following:
- announcement module on the home page  
(for which I would suggest a distinct style to set it apart)
- an events page that (for now) will focus mostly on hacknight, but which should be designed to facilitate the addition of other event types

**Comment by brb3** [comment]
We should have a an ical file thingy that you can download to put the Hacknight on your calendar.

**Comment by brb3** [comment]
Here's a calendar invite thingy for Google Calendar: https://calendar.google.com/calendar/hosted/brb3.org/event?action=TEMPLATE&tmeid=NXRzYnQ4MXNzOWxqNHJpZzFmNHRmaThjZzRfMjAxNzA1MDNUMjIwMDAwWiBib2JieUBicmIzLm9yZw&tmsrc=bobby%40brb3.org

**Comment by ryanmaynard** [comment]
[AddToCalendar Button](http://addtocalendar.com/)

**Comment by brb3** [comment]
Looks like the AddToCalendar widget thingy doesn't have support for recurring events @ryanmaynard

**Comment by ryanmaynard** [comment]
> doesn't have support for recurring events 

My mistake. I meant to post [AddEvent](https://www.addevent.com/). The free/personal plan does apply to open source, or it did a few years ago. 

To be clear, I'm not saying this is what should be used. Just making sure everyone knows it exists, in case it proves useful/easier.

**Comment by agarzola** [comment]
This was done in #106 and is live.
