### ISSUE TITLE
Explore blog post tagging feature

### ISSUE THREAD

**Issue by agarzola** [devanooga/devanooga.com#84]
This is more of an epic, as it should cover:
- [x] figuring out what the “Jekyll way” is to implement tags
- [x] adding tags across existing blog posts
- [x] design the appearance of tags on a blog post and post summary (if at all)
- [x] implement tag pages (i.e. what you see when you click on a tag)
- [x] evaluate options for implementing a tags list on the blog  
Maybe as a sidebar thing? Maybe it’s a dedicated `/tags` page listing all tags with a JS-powered search field that narrows tags down as you type?
- [ ] determine a tag-creation standard  
Should tags be nested like `parent_tag:child_tag` syntax, like `devops:hosting` and `frontend:js_frameworks`? Tags can quickly turn into an impenetrable mess; I suggest we develop a strong, flexible standard to help keep them useful.

**Comment by ryanmaynard** [comment]
> figuring out what the “Jekyll way” is to implement tags

You just place tags in the YAML Front Matter. 

> adding tags across existing blog posts

Fairly easy to do, since we're currently sitting at two posts. 

Your last two are great questions. 

1. Where to place list of tags
2. tag standard: allow nested tags? etc

**Comment by agarzola** [comment]
As per conversation with @t-richards during hacknight earlier, nested tags is probably a can of worms. However, there is value in defining a standard against which reviewers can test a post submission to avoid things like multiple tags for a single topic; e.g. some posts with a `blog` tag and others with a `blogging` tag, or some with `tdd` and others with `writing-tests`).

Other good points brought up by Tom:
- a post should have no more than five tags
- maybe set up a CI server (Travis?) to automate basic tests:
    - that there are tags
    - that the number of tags doesn’t exceed 5
    - that the post doesn’t introduce duplicate tags  
      _(so like using a library that finds fuzzy duplicates with stemming and the like)_


Ultimately, reviewers will have to be vigilant about this so that tags are actually useful, and not a complete fucking mess.

**Comment by agarzola** [comment]
I’m looking into generating tag pages and found [this post](http://charliepark.org/tags-in-jekyll/), which seems to describe exactly what we’re going for here. I’ll work on that feature and submit a PR to @t-richards’s branch (like a pull-request matryoshka), so that it gets rolled into his feature branch.

To that end, I propose a url scheme that looks like this:
- `/blog/tags` shows a tag cloud or list (which we could later enhance with some form of filtering on the client side).
- `/blog/tags/tag-name` shows all posts with a `tag-name` tag.

If anybody thinks there’s a better route, I’d love to hear it.

**Comment by brb3** [comment]
Btw, "matryoshka" are "Russian Dolls". You're welcome.

**Comment by agarzola** [comment]
Point taken. I updated my comment to include a link for those incapable of rolling their Rs.

**Comment by ryanmaynard** [comment]
> Btw, "matryoshka" are "Russian Dolls". You're welcome.

Historically, I have learned the most (about anything in general) by being around people that don't mind admitting "I don't know" or "I'm just now learning this". 

Also, thanks for teaching me that word. Next step is to google how to pronounce it.
