### ISSUE TITLE
Privacy Information

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.com#87]
Protecting our members privacy should generally be a top concern, so few things we'd probably want to lay out somewhere (our CoC?).

- Contact form submissions can be viewed by all admins.
- Channel chat logs will be persisted (when we get 501(c)(3)), at least for certain channels (list them).
- Email account is accessible by admins.

Personal chat logs aren't accessible by us I think under any circumstances that aren't for compliance but I'll check on that.

**Comment by DigTK** [comment]
From what I can find personal chat logs are only available to admins via compliance export

**Comment by StrangeWill** [comment]
This was done in a PR way back, we're good.
