### ISSUE TITLE
Re-design blog post URLs

### ISSUE THREAD

**Issue by agarzola** [devanooga/devanooga.com#90]
I hadn’t noticed this before, but blog post URLs are not name-spaced to `/blog/`, so rather than. This is great as a default because Jekyll is designed to be a blog by default, but we have a dedicated blog _section_, so it makes sense for posts to live within that directory, like so:
```
devanooga.com/blog/2017/04/22/annoying-mastodon-users-with-a-bot
```

As part of this change, we’ll need to provide `301` redirects for any existing blog post URLs, so that they’re not broken. The sooner we do this, the better, in my opinion.

---
While we’re on the subject of blog post URLs, how does the community feel about dates in blog post URLs? I like that they provide context to a URL, but if there’s any good arguments not to include them, now’s the time to have that conversation.

**Comment by brb3** [comment]
I like the dates in the URLs, but [SearchEngineLand](http://searchengineland.com/four-reasons-to-avoid-using-dates-in-urls-13152) says that's a "no-no".

Probably should wait to hear from the marketing folks like Kate or @ryanmaynard.

**Comment by agarzola** [comment]
I wouldn’t call the date of publication irrelevant (maybe _less_ relevant than the title), nor do I agree it necessarily suggest the content is old or stale. That said, it’s true that when the URL is truncated in service X or Y, having a date only help push the more relevant title towards getting cut.
