### ISSUE TITLE
Travis CI and testing

### ISSUE THREAD

**Issue by agarzola** [devanooga/devanooga.com#92]
I added TravisCI to this repo after a conversation with @t-richards in which he suggested some tests could be written to help validate blog post tags for max number of tags and (possibly, ideally) avoid tag name “duplication” with word stemming (`blog` vs `blogging`, `bot` vs `bots`). I didn’t realize this would make every PR fail (for lack of `.travis.yrl`).

¯\\\_(ツ)_/¯

So I guess it’s time to start writing tests?

**Comment by brb3** [comment]
Sounds like it. I can start a PR to add a `.travis.yml` and basic tests.

**Comment by agarzola** [comment]
Here’s an interesting test I’ve been thinking of: if the `author` field in a post’s front matter doesn’t have a member’s username (tying it to their profile), check that its value is not the same as an existing member’s full name. If it _is_, the test fails with a message indicating that the author field should point to that member’s username. Examples:

If a post’s front matter has this:
```
author: Ryan Maynard
```
this test fails with a message like:
>Author has a member profile. Use their username instead.

But a post with this in the front matter:
```
author: Testy McTestface
```
passes the test because none of the members in the site has _Testy McTestface_ as their full name.

**Comment by agarzola** [comment]
This was implemented in #93.
